### PR TITLE
Hotfix - add PYTHONPATH to `run_stage` environment and handle missing config file exceptions

### PR DESCRIPTION
**Pull request by AlexIoannides**
This hotfix targets two separate issues:
1. While putting together an [example pipeline project](https://github.com/bodywork-ml/ml-pipeline-engineering) for the next blog post, I run into several issues when using a `pipeline/` folder for the pipeline code and then trying to import modules as if `pipeline` was a Python package module. These can be solved by adding the project's root directory to `PYTHONPATH`. While this isn't strictly necessary, it leads to a **much** better developer experience (and probably reduces the risk of confusion).
- By accident, I tried to run a workflow without a `bodywork.yaml` file and I got a cascade of exceptions in the face. This is because `BodyworkConfig` throws a `FileExistsError` exception, which we don't handle in `run_workflow`. I thought about creating a custom exception that inherits from `BodyworkConfigError`, but that seemed overkill (need your opinion here).

### CODE REVIEW

**Review by Marios85 — CHANGES_REQUESTED** [review]
For consistency that should be covered as a BodyworkConfig error as all other config errors are raised as such. I do not think there is a need to create a custom exception and just raising it as the Base Exception is sufficient.

**Comment by AlexIoannides** [comment]
I decided to write a custom exception in the end...

**Review by Marios85 — APPROVED** [review]
All good!

**Comment by AlexIoannides** [comment]
Thank you!

**Pull request merged**
